version: '3'

services:
  db:
    image: postgres:9.6

  redis:
    image: redis

  django:
    build: .
    command: python3 djangoproj/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis