# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 12:39
from __future__ import unicode_literals

import dirtyfields.dirtyfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(null=True)),
                ('author_name', models.CharField(max_length=255, null=True)),
                ('author_slug', models.CharField(max_length=255, null=True)),
                ('lang', models.CharField(max_length=2, null=True)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
